# include:
#   - ../compose.pgsql.yaml

services:
  telepy:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - telesignal_network
    # depends_on:
    #   - db
    volumes:
      - ./:/app
    command: [ "python", "-u", "src/stream_quotes.py" ]
networks:
  telesignal_network:
    external: true
